<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <Folder Include="Validators\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CarMaintenanceDiary.Core\CarMaintenanceDiary.Core.csproj" />
    <ProjectReference Include="..\CarMaintenanceDiary.Infrastructure\CarMaintenanceDiary.Infrastructure.csproj" />
    <ProjectReference Include="..\CarMaintenanceDiary.Shared\CarMaintenanceDiary.Shared.csproj" />
  </ItemGroup>

</Project>
